// <auto-generated />
namespace NorthWind_ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version110));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201533095_Version1.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
